// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by `pnpm db:types` from the database schema. Do not edit by hand.
import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type GeneratedAlways<T> = ColumnType<T, never, never>;
export type Timestamp = ColumnType<string, string | Date, string | Date>;
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type Json = ColumnType<JsonValue, JsonValue | string, JsonValue | string>;

export interface AgentClients {
  id: Generated<string>;
  workspace_id: string | null;
  client_id: string;
  client_secret_hash: string | null;
  name: string;
  logo_url: string | null;
  homepage_url: string | null;
  cimd_url: string | null;
  owner_user_id: string | null;
  kind: string;
  registration: Generated<string>;
  redirect_uris: Generated<string[]>;
  scopes: Generated<string[]>;
  tool_allowlist: string[] | null;
  rate_limit_per_min: Generated<number>;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface AgentGrants {
  id: Generated<string>;
  client_id: string;
  user_id: string;
  workspace_id: string | null;
  scopes: Generated<string[]>;
  status: Generated<string>;
  expires_at: Timestamp | null;
  last_used_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface AgentPolicies {
  workspace_id: string;
  ai_use: Generated<string>;
  disclosure_prompt: Generated<string>;
  reviewer_assist: Generated<boolean>;
  agent_submissions_enabled: Generated<boolean>;
  mcp_enabled: Generated<boolean>;
  a2a_enabled: Generated<boolean>;
  llm_provider: string | null;
  llm_key_ref: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface AgentTasks {
  id: Generated<string>;
  workspace_id: string | null;
  client_id: string | null;
  user_id: string | null;
  protocol: string;
  skill: string;
  context_id: string | null;
  state: Generated<string>;
  input: Generated<Json>;
  output: Json | null;
  history: Generated<Json>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Agreements {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  status: Generated<string>;
  document_path: string | null;
  document_hash: string | null;
  body_md: string | null;
  sent_at: Timestamp | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface AnalyticsBudgetByProgram {
  workspace_id: string | null;
  program_id: string | null;
  program_name: string | null;
  fiscal_year: number | null;
  currency: string | null;
  row_key: string | null;
  budget_cents: number | null;
  committed_cents: number | null;
  paid_cents: number | null;
  unpaid_commitments_cents: number | null;
  remaining_cents: number | null;
  awards: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsCashflowForecast {
  workspace_id: string | null;
  month: string | null;
  currency: string | null;
  scheduled_cents: number | null;
  installments: number | null;
  paid_cents: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsDemographics {
  workspace_id: string | null;
  question: string | null;
  answer: string | null;
  responses: number | null;
  suppressed: boolean | null;
  question_respondents: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsOutcomes {
  workspace_id: string | null;
  indicator_id: string | null;
  indicator: string | null;
  unit: string | null;
  program_id: string | null;
  program_name: string | null;
  total_value: number | null;
  awards_reporting: number | null;
  latest_period_end: string | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsPipelineFunnel {
  workspace_id: string | null;
  opportunity_id: string | null;
  opportunity_title: string | null;
  opportunity_status: string | null;
  started: number | null;
  submitted: number | null;
  reviewed: number | null;
  awarded: number | null;
  declined: number | null;
  withdrawn_or_ineligible: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsPortfolioByCause {
  workspace_id: string | null;
  cause: string | null;
  cause_label: string | null;
  currency: string | null;
  committed_cents: number | null;
  awards: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsPortfolioByCounty {
  workspace_id: string | null;
  county: string | null;
  currency: string | null;
  committed_cents: number | null;
  awards: number | null;
  grantees: number | null;
  refreshed_at: Timestamp | null;
}

export interface AnalyticsTimeInStage {
  workspace_id: string | null;
  status: string | null;
  completed: number | null;
  avg_days: number | null;
  median_days: number | null;
  p90_days: number | null;
  current: number | null;
  current_avg_days: number | null;
  refreshed_at: Timestamp | null;
}

export interface ApiKeys {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  prefix: string;
  key_hash: string;
  scopes: Generated<string[]>;
  owner_id: string | null;
  agent_client_id: string | null;
  expires_at: Timestamp | null;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicantExtensions {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  new_deadline: Timestamp;
  reason: string | null;
  granted_by: string | null;
  created_at: Generated<Timestamp>;
}

export interface ApplicantOrgMembers {
  id: Generated<string>;
  org_id: string;
  user_id: string;
  role: Generated<string>;
  title: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicantOrgs {
  id: Generated<string>;
  legal_name: string;
  dba_name: string | null;
  ein: string | null;
  uei: string | null;
  org_type: Generated<string>;
  mission: string | null;
  annual_budget_cents: number | null;
  website: string | null;
  phone: string | null;
  email: string | null;
  counties: Generated<string[]>;
  fiscal_sponsor_name: string | null;
  fiscal_sponsor_ein: string | null;
  ein_verified_at: Timestamp | null;
  irs_status: Json | null;
  tags: Generated<string[]>;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicationCollaborators {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  user_id: string | null;
  email: string;
  role: Generated<string>;
  status: Generated<string>;
  token_hash: string | null;
  invited_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicationComments {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  author_id: string | null;
  field_path: string | null;
  body: string;
  resolved_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicationDuplicateDismissals {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  other_application_id: string;
  reason: string | null;
  dismissed_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ApplicationSubmissions {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  competition_id: string;
  submitted_at: Generated<Timestamp>;
  submitted_by: string | null;
  submitted_by_agent_client_id: string | null;
  responses: Json;
  org_profile: Generated<Json>;
  form_versions: Generated<Json>;
  attestation: Generated<Json>;
  receipt_number: string;
  content_hash: string;
}

export interface Applications {
  id: Generated<string>;
  workspace_id: string;
  opportunity_id: string;
  competition_id: string;
  applicant_org_id: string | null;
  applicant_user_id: string;
  reference_number: string;
  title: string | null;
  status: Generated<string>;
  requested_amount_cents: number | null;
  currency: Generated<string>;
  submitted_at: Timestamp | null;
  deadline_override_at: Timestamp | null;
  ai_disclosure: string | null;
  created_via: Generated<string>;
  submitted_via: string | null;
  submitted_by_agent_client_id: string | null;
  duplicate_of: string | null;
  previous_application_id: string | null;
  info_requested_at: Timestamp | null;
  info_request_note: string | null;
  tags: Generated<string[]>;
  custom_fields: Generated<Json>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
  search: GeneratedAlways<string | null>;
}

export interface ApprovalRequests {
  id: Generated<string>;
  workspace_id: string;
  action_id: string;
  input: Json;
  preview: Json;
  risk_tier: string;
  requested_by_client_id: string | null;
  requester_name: string;
  on_behalf_of: string;
  audience: Generated<string>;
  status: Generated<string>;
  entity_type: string | null;
  entity_id: string | null;
  token_hash: string | null;
  expires_at: Generated<Timestamp>;
  decided_by: string | null;
  decided_at: Timestamp | null;
  result: Json | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Attachments {
  id: Generated<string>;
  workspace_id: string;
  application_id: string | null;
  report_submission_id: string | null;
  field_path: string | null;
  file_name: string;
  content_type: string;
  size_bytes: number;
  storage_path: string;
  sha256: string | null;
  scan_status: Generated<string>;
  status: Generated<string>;
  uploaded_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface AuditLog {
  id: Generated<string>;
  workspace_id: string | null;
  occurred_at: Generated<Timestamp>;
  actor_type: string;
  actor_id: string | null;
  actor_name: string | null;
  agent_client_id: string | null;
  on_behalf_of: string | null;
  on_behalf_of_name: string | null;
  action: string;
  entity_type: string | null;
  entity_id: string | null;
  before: Json | null;
  after: Json | null;
  risk_tier: string | null;
  approval_request_id: string | null;
  ip: string | null;
  user_agent: string | null;
  request_id: string | null;
}

export interface AwardConditions {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  body: string;
  due_date: string | null;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Awards {
  id: Generated<string>;
  workspace_id: string;
  application_id: string | null;
  program_id: string | null;
  opportunity_id: string | null;
  applicant_org_id: string | null;
  parent_award_id: string | null;
  kind: Generated<string>;
  amendment_status: string | null;
  reference: string;
  title: string;
  purpose: string | null;
  amount_cents: number;
  currency: Generated<string>;
  start_date: string | null;
  end_date: string | null;
  fiscal_year: number | null;
  status: Generated<string>;
  agreement_pending: Generated<boolean>;
  on_hold: Generated<boolean>;
  hold_reason: string | null;
  report_overdue: Generated<boolean>;
  disbursed_cents: Generated<number>;
  expenditure_responsibility: Generated<boolean>;
  grant_to_individual: Generated<boolean>;
  relationship_note: string | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface BankAccounts {
  id: Generated<string>;
  workspace_id: string;
  connection_id: string;
  provider_account_id: string;
  name: string;
  mask: string | null;
  kind: Generated<string>;
  available_cents: number | null;
  current_cents: number | null;
  currency: Generated<string>;
  balance_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface BankConnections {
  id: Generated<string>;
  workspace_id: string;
  provider: string;
  mode: Generated<string>;
  environment: Generated<string>;
  secret_ref: string | null;
  webhook_id: string | null;
  webhook_secret_ref: string | null;
  webhook_status: Generated<string>;
  status: Generated<string>;
  last_synced_at: Timestamp | null;
  connected_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface BankTransactions {
  id: Generated<string>;
  workspace_id: string;
  bank_account_id: string | null;
  provider_transaction_id: string;
  amount_cents: number;
  currency: Generated<string>;
  status: string;
  kind: string | null;
  counterparty_name: string | null;
  memo: string | null;
  note: string | null;
  posted_at: Timestamp | null;
  raw: Generated<Json>;
  payment_id: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface BulkMessages {
  id: Generated<string>;
  workspace_id: string;
  template_key: string | null;
  segment: Generated<Json>;
  subject: string;
  body_md: string;
  recipient_count: Generated<number>;
  status: Generated<string>;
  created_by: string | null;
  created_by_agent_client_id: string | null;
  sent_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ChangeRequests {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  requirement_id: string | null;
  kind: string;
  details: Generated<Json>;
  reason: string;
  status: Generated<string>;
  requested_by: string | null;
  requested_by_agent_client_id: string | null;
  decided_by: string | null;
  decided_at: Timestamp | null;
  decision_note: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface CoiDeclarations {
  id: Generated<string>;
  workspace_id: string;
  assignment_id: string;
  reviewer_id: string;
  has_conflict: boolean;
  explanation: string | null;
  declared_at: Generated<Timestamp>;
}

export interface CompetitionForms {
  id: Generated<string>;
  workspace_id: string;
  competition_id: string;
  form_id: string;
  form_version_id: string | null;
  position: Generated<number>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface CompetitionInvites {
  id: Generated<string>;
  workspace_id: string;
  competition_id: string;
  applicant_org_id: string | null;
  email: string | null;
  from_application_id: string | null;
  status: Generated<string>;
  invited_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Competitions {
  id: Generated<string>;
  workspace_id: string;
  opportunity_id: string;
  name: string;
  description: string | null;
  stage_order: Generated<number>;
  access: Generated<string>;
  status: Generated<string>;
  opens_at: Timestamp | null;
  closes_at: Timestamp | null;
  grace_minutes: Generated<number>;
  submission_cap: number | null;
  per_org_limit: Generated<number>;
  allow_extensions: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface CustomFieldDefinitions {
  id: Generated<string>;
  workspace_id: string;
  entity: string;
  key: string;
  label: string;
  field_type: string;
  options: Generated<Json>;
  required: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Decisions {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  outcome: string;
  reason: string | null;
  recommended_amount_cents: number | null;
  is_final: Generated<boolean>;
  recorded_by: string | null;
  recorded_at: Generated<Timestamp>;
  letter_sent_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface DemographicResponses {
  id: Generated<string>;
  workspace_id: string;
  application_id: string | null;
  applicant_org_id: string | null;
  data: Generated<Json>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface DeploymentRequests {
  id: Generated<string>;
  workspace_id: string;
  requested_by: string | null;
  kind: string;
  desired_domain: string | null;
  details: string;
  contact_email: string;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface DevOutbox {
  id: Generated<string>;
  workspace_id: string | null;
  to_email: string;
  from_email: string;
  subject: string;
  html: string | null;
  text: string | null;
  tags: Generated<Json>;
  created_at: Generated<Timestamp>;
}

export interface DiligenceChecks {
  id: Generated<string>;
  workspace_id: string;
  applicant_org_id: string;
  award_id: string | null;
  kind: string;
  status: string;
  result: Generated<Json>;
  checked_at: Generated<Timestamp>;
  reviewed_by: string | null;
  reviewed_at: Timestamp | null;
  note: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface DocketItems {
  id: Generated<string>;
  workspace_id: string;
  docket_id: string;
  application_id: string;
  position: Generated<number>;
  recommended_amount_cents: number | null;
  recommendation: string | null;
  outcome: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Dockets {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  meeting_at: Timestamp | null;
  status: Generated<string>;
  quorum: Generated<number>;
  board_book_path: string | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface EligibilityResults {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  rule_id: string | null;
  question: string;
  passed: boolean;
  answer: Json | null;
  source: Generated<string>;
  evaluated_at: Generated<Timestamp>;
}

export interface EligibilityRules {
  id: Generated<string>;
  workspace_id: string;
  opportunity_id: string;
  position: Generated<number>;
  question: string;
  help_text: string | null;
  kind: string;
  config: Generated<Json>;
  knockout_message: string;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface EmailDeliveries {
  id: Generated<string>;
  workspace_id: string | null;
  bulk_message_id: string | null;
  template_key: string | null;
  to_email: string;
  subject: string;
  provider: string;
  provider_message_id: string | null;
  status: Generated<string>;
  error: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface EmailEvents {
  id: Generated<string>;
  workspace_id: string | null;
  delivery_id: string | null;
  provider: string;
  provider_event_id: string;
  event: string;
  recipient: string | null;
  payload: Generated<Json>;
  occurred_at: Generated<Timestamp>;
}

export interface EmailTemplates {
  id: Generated<string>;
  workspace_id: string;
  key: string;
  name: string;
  subject: string;
  body_md: string;
  merge_fields: Generated<string[]>;
  updated_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Exports {
  id: Generated<string>;
  workspace_id: string;
  kind: string;
  params: Generated<Json>;
  format: Generated<string>;
  status: Generated<string>;
  file_path: string | null;
  error: string | null;
  requested_by: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface FormResponses {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  form_id: string;
  form_version_id: string;
  data: Generated<Json>;
  field_updated_at: Generated<Json>;
  etag: Generated<string>;
  updated_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface FormTemplates {
  id: Generated<string>;
  workspace_id: string | null;
  name: string;
  description: string | null;
  kind: Generated<string>;
  builder_model: Json;
  source: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface FormVersions {
  id: Generated<string>;
  workspace_id: string;
  form_id: string;
  version: number;
  status: Generated<string>;
  builder_model: Generated<Json>;
  json_schema: Generated<Json>;
  ui_schema: Generated<Json>;
  mapping_to_cg: Generated<Json>;
  mapping_from_cg: Generated<Json>;
  field_meta: Generated<Json>;
  change_note: string | null;
  published_at: Timestamp | null;
  published_by: string | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Forms {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  kind: Generated<string>;
  description: string | null;
  status: Generated<string>;
  current_version_id: string | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface GranteeProfiles {
  id: Generated<string>;
  workspace_id: string;
  applicant_org_id: string;
  tags: Generated<string[]>;
  relationship_owner_id: string | null;
  summary: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface IdempotencyKeys {
  key: string;
  workspace_id: string | null;
  actor_id: string | null;
  action_id: string;
  request_hash: string;
  response: Json | null;
  created_at: Generated<Timestamp>;
}

export interface IndicatorValues {
  id: Generated<string>;
  workspace_id: string;
  indicator_id: string;
  award_id: string;
  report_submission_id: string | null;
  value: number;
  period_end: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Indicators {
  id: Generated<string>;
  workspace_id: string;
  program_id: string | null;
  name: string;
  unit: Generated<string>;
  description: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Installments {
  id: Generated<string>;
  workspace_id: string;
  schedule_id: string;
  award_id: string;
  position: number;
  due_date: string;
  amount_cents: number;
  currency: Generated<string>;
  condition: string | null;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface InternalNotes {
  id: Generated<string>;
  workspace_id: string;
  entity_type: string;
  entity_id: string;
  author_id: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Invitations {
  id: Generated<string>;
  workspace_id: string;
  email: string;
  role: string;
  token_hash: string;
  status: Generated<string>;
  invited_by: string | null;
  expires_at: Generated<Timestamp>;
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface IrsExemptOrgs {
  ein: string;
  name: string;
  city: string | null;
  state: string | null;
  subsection: string | null;
  foundation_code: string | null;
  deductibility: string | null;
  status: Generated<string>;
  ruling_date: string | null;
  pub78: Generated<boolean>;
  ntee: string | null;
  source: Generated<string>;
  imported_at: Generated<Timestamp>;
}

export interface Messages {
  id: Generated<string>;
  workspace_id: string;
  thread_id: string;
  author_id: string | null;
  author_side: string;
  agent_client_id: string | null;
  body: string;
  read_by_applicant_at: Timestamp | null;
  read_by_staff_at: Timestamp | null;
  created_at: Generated<Timestamp>;
}

export interface NotificationRules {
  id: Generated<string>;
  workspace_id: string;
  event_type: string;
  channel: string;
  audience: string;
  template_key: string | null;
  offset_days: number | null;
  enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Notifications {
  id: Generated<string>;
  workspace_id: string | null;
  user_id: string;
  kind: string;
  title: string;
  body: string | null;
  link: string | null;
  read_at: Timestamp | null;
  created_at: Generated<Timestamp>;
}

export interface OauthAuthorizationCodes {
  code_hash: string;
  client_id: string;
  user_id: string;
  workspace_id: string | null;
  redirect_uri: string;
  scopes: string[];
  resource: string | null;
  code_challenge: string;
  code_challenge_method: Generated<string>;
  expires_at: Timestamp;
  used_at: Timestamp | null;
  created_at: Generated<Timestamp>;
}

export interface OauthPendingAuthorizations {
  id: Generated<string>;
  client_id: string;
  workspace_id: string | null;
  redirect_uri: string;
  scopes: string[];
  resource: string | null;
  state: string | null;
  code_challenge: string;
  expires_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
}

export interface Opportunities {
  id: Generated<string>;
  workspace_id: string;
  program_id: string | null;
  slug: string;
  title: string;
  status: Generated<string>;
  visibility: Generated<string>;
  summary: string | null;
  description_md: string | null;
  eligibility_md: string | null;
  guidelines_md: string | null;
  faq: Generated<Json>;
  funding_total_cents: number | null;
  award_min_cents: number | null;
  award_max_cents: number | null;
  expected_award_count: number | null;
  currency: Generated<string>;
  applicant_types: Generated<string[]>;
  cause_terms: Generated<string[]>;
  geography_terms: Generated<string[]>;
  population_terms: Generated<string[]>;
  forecast_at: Timestamp | null;
  opens_at: Timestamp | null;
  closes_at: Timestamp | null;
  decision_expected_on: string | null;
  contact_email: string | null;
  distribution: Generated<Json>;
  custom_fields: Generated<Json>;
  published_at: Timestamp | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
  search: GeneratedAlways<string | null>;
}

export interface OpportunitySubscriptions {
  id: Generated<string>;
  workspace_id: string;
  opportunity_id: string;
  user_id: string;
  notified_at: Timestamp | null;
  created_at: Generated<Timestamp>;
}

export interface OrgAddresses {
  id: Generated<string>;
  org_id: string;
  kind: Generated<string>;
  line1: string;
  line2: string | null;
  city: string;
  state: string;
  postal_code: string;
  country: Generated<string>;
  county: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface OrgDocuments {
  id: Generated<string>;
  org_id: string;
  doc_type: string;
  title: string;
  storage_path: string;
  content_type: string;
  size_bytes: number;
  sha256: string | null;
  expires_on: string | null;
  scan_status: Generated<string>;
  uploaded_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Outbox {
  id: Generated<number>;
  workspace_id: string | null;
  event_type: string;
  entity_type: string | null;
  entity_id: string | null;
  payload: Generated<Json>;
  created_at: Generated<Timestamp>;
  processed_at: Timestamp | null;
  attempts: Generated<number>;
  last_error: string | null;
}

export interface PanelNotes {
  id: Generated<string>;
  workspace_id: string;
  panel_id: string | null;
  application_id: string;
  author_id: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Panels {
  id: Generated<string>;
  workspace_id: string;
  stage_id: string;
  name: string;
  meets_at: Timestamp | null;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Payees {
  id: Generated<string>;
  workspace_id: string;
  applicant_org_id: string;
  provider: Generated<string>;
  provider_recipient_id: string | null;
  invite_id: string | null;
  onboarding_url: string | null;
  invite_status: string | null;
  status: Generated<string>;
  contact_email: string;
  payment_methods: Generated<string[]>;
  invited_at: Timestamp | null;
  ready_at: Timestamp | null;
  last_polled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface PaymentApprovals {
  id: Generated<string>;
  workspace_id: string;
  batch_id: string;
  approver_id: string;
  decision: string;
  aal: string;
  note: string | null;
  created_at: Generated<Timestamp>;
}

export interface PaymentBatches {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  source_account_id: string | null;
  method: Generated<string>;
  status: Generated<string>;
  requires_second_approval: Generated<boolean>;
  total_cents: Generated<number>;
  created_by: string;
  created_by_agent_client_id: string | null;
  approved_by: string | null;
  approved_at: Timestamp | null;
  second_approved_by: string | null;
  second_approved_at: Timestamp | null;
  submitted_at: Timestamp | null;
  note: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface PaymentSchedules {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Payments {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  installment_id: string | null;
  batch_id: string | null;
  payee_id: string | null;
  source_account_id: string | null;
  method: Generated<string>;
  amount_cents: number;
  currency: Generated<string>;
  fee_cents: Generated<number>;
  status: Generated<string>;
  rail: Generated<string>;
  rail_ref: string | null;
  rail_transaction_id: string | null;
  idempotency_key: Generated<string>;
  hold_reason: string | null;
  failure_reason: string | null;
  memo: string | null;
  external_reference: string | null;
  requested_at: Timestamp | null;
  sent_at: Timestamp | null;
  reconciled_at: Timestamp | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface PersonalAccessTokens {
  id: Generated<string>;
  user_id: string;
  workspace_id: string | null;
  agent_client_id: string | null;
  name: string;
  prefix: string;
  token_hash: string;
  scopes: Generated<string[]>;
  audience: Generated<string[]>;
  expires_at: Timestamp | null;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface PlatformOperators {
  user_id: string;
  role: Generated<string>;
  created_at: Generated<Timestamp>;
}

export interface Profiles {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  locale: Generated<string>;
  notification_prefs: Generated<Json>;
  deletion_requested_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ProgramAccounts {
  id: Generated<string>;
  workspace_id: string;
  program_id: string;
  bank_account_id: string;
  is_default: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ProgramBudgets {
  id: Generated<string>;
  workspace_id: string;
  program_id: string;
  fiscal_year: number;
  amount_cents: number;
  currency: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Programs {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  slug: string;
  description: string | null;
  status: Generated<string>;
  cause_area: string | null;
  lead_user_id: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface PublicAwards {
  id: string | null;
  workspace_id: string | null;
  reference: string | null;
  title: string | null;
  purpose: string | null;
  currency: string | null;
  start_date: string | null;
  end_date: string | null;
  fiscal_year: number | null;
  created_at: Timestamp | null;
  last_modified_at: Timestamp | null;
  status: string | null;
  amount_cents: number | null;
  recipient_name: string | null;
  recipient_city: string | null;
  recipient_state: string | null;
  recipient_county: string | null;
  program_name: string | null;
  opportunity_id: string | null;
}

export interface PublicPrograms {
  id: string | null;
  workspace_id: string | null;
  name: string | null;
  slug: string | null;
  description: string | null;
  cause_area: string | null;
}

export interface QuestionBankItems {
  id: Generated<string>;
  workspace_id: string | null;
  label: string;
  field: Json;
  tags: Generated<string[]>;
  cg_path: string | null;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface RailEvents {
  id: Generated<string>;
  workspace_id: string | null;
  provider: string;
  event_id: string;
  event_type: string;
  payload: Json;
  signature_valid: boolean;
  received_at: Generated<Timestamp>;
  processed_at: Timestamp | null;
  error: string | null;
}

export interface RateLimitBuckets {
  key: string;
  window_start: Timestamp;
  count: Generated<number>;
}

export interface ReconExceptions {
  id: Generated<string>;
  workspace_id: string;
  kind: string;
  bank_transaction_id: string | null;
  payment_id: string | null;
  details: string;
  status: Generated<string>;
  resolved_by: string | null;
  resolved_at: Timestamp | null;
  note: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ReportRequirements {
  id: Generated<string>;
  workspace_id: string;
  award_id: string;
  form_id: string | null;
  title: string;
  kind: Generated<string>;
  due_date: string;
  status: Generated<string>;
  holds_payments: Generated<boolean>;
  reminder_sent_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ReportSubmissions {
  id: Generated<string>;
  workspace_id: string;
  requirement_id: string;
  award_id: string;
  form_version_id: string | null;
  data: Generated<Json>;
  status: Generated<string>;
  submitted_by: string | null;
  submitted_by_agent_client_id: string | null;
  submitted_at: Timestamp | null;
  reviewer_id: string | null;
  review_note: string | null;
  reviewed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ReviewAssignments {
  id: Generated<string>;
  workspace_id: string;
  stage_id: string;
  application_id: string;
  reviewer_id: string;
  status: Generated<string>;
  assigned_by: string | null;
  due_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ReviewScores {
  id: Generated<string>;
  workspace_id: string;
  review_id: string;
  criterion_id: string;
  score: number;
  comment: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface ReviewStages {
  id: Generated<string>;
  workspace_id: string;
  competition_id: string;
  rubric_id: string | null;
  name: string;
  position: Generated<number>;
  blind: Generated<boolean>;
  reviewers_per_application: Generated<number>;
  due_at: Timestamp | null;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Reviews {
  id: Generated<string>;
  workspace_id: string;
  assignment_id: string;
  status: Generated<string>;
  overall_comment: string | null;
  private_note: string | null;
  recommendation: string | null;
  weighted_score: number | null;
  submitted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface RubricCriteria {
  id: Generated<string>;
  workspace_id: string;
  rubric_id: string;
  position: Generated<number>;
  label: string;
  guidance: string | null;
  weight_pct: number;
  scale_min: Generated<number>;
  scale_max: Generated<number>;
  scale_labels: Generated<Json>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Rubrics {
  id: Generated<string>;
  workspace_id: string;
  name: string;
  description: string | null;
  status: Generated<string>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface SanctionsEntries {
  id: Generated<string>;
  source: Generated<string>;
  source_uid: string;
  name: string;
  name_normalized: string;
  entry_type: string | null;
  programs: Generated<string[]>;
  remarks: string | null;
  imported_at: Generated<Timestamp>;
}

export interface SanctionsScreenings {
  id: Generated<string>;
  workspace_id: string;
  applicant_org_id: string | null;
  award_id: string | null;
  payment_id: string | null;
  context: string;
  query_name: string;
  best_score: Generated<number>;
  matches: Generated<Json>;
  status: string;
  reviewed_by: string | null;
  reviewed_at: Timestamp | null;
  review_note: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface SavedViews {
  id: Generated<string>;
  workspace_id: string;
  user_id: string;
  surface: string;
  name: string;
  config: Generated<Json>;
  shared: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Signatures {
  id: Generated<string>;
  workspace_id: string;
  agreement_id: string;
  signer_id: string;
  signer_role: string;
  typed_name: string;
  attestation: string;
  signed_at: Generated<Timestamp>;
  ip: string | null;
  user_agent: string | null;
  document_hash: string;
}

export interface SiteVisits {
  id: Generated<string>;
  workspace_id: string;
  applicant_org_id: string;
  award_id: string | null;
  visited_on: string;
  visited_by: string | null;
  summary: string;
  follow_ups: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface StatusHistory {
  id: Generated<string>;
  workspace_id: string;
  application_id: string;
  from_status: string | null;
  to_status: string;
  reason: string | null;
  actor_type: Generated<string>;
  actor_id: string | null;
  actor_name: string | null;
  visible_to_applicant: Generated<boolean>;
  created_at: Generated<Timestamp>;
}

export interface SupportAccessGrants {
  id: Generated<string>;
  workspace_id: string;
  operator_user_id: string;
  granted_by: string | null;
  reason: string;
  expires_at: Timestamp;
  revoked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface TaxonomyTerms {
  id: Generated<string>;
  workspace_id: string;
  kind: string;
  code: string;
  label: string;
  parent_id: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Threads {
  id: Generated<string>;
  workspace_id: string;
  application_id: string | null;
  award_id: string | null;
  subject: string;
  created_by: string | null;
  last_message_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Votes {
  id: Generated<string>;
  workspace_id: string;
  docket_item_id: string;
  voter_id: string;
  vote: string;
  recorded_at: Generated<Timestamp>;
}

export interface WebhookDeliveries {
  id: Generated<string>;
  workspace_id: string;
  endpoint_id: string;
  event_id: string;
  event_type: string;
  payload: Json;
  attempt: Generated<number>;
  status: Generated<string>;
  response_status: number | null;
  response_snippet: string | null;
  next_attempt_at: Generated<Timestamp | null>;
  delivered_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface WebhookEndpoints {
  id: Generated<string>;
  workspace_id: string;
  url: string;
  description: string | null;
  events: Generated<string[]>;
  secret_ref: string;
  status: Generated<string>;
  created_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface WorkspaceBrand {
  workspace_id: string;
  display_name: string;
  logo_path: string | null;
  logo_dark_path: string | null;
  favicon_path: string | null;
  primary_color: Generated<string>;
  accent_color: Generated<string>;
  heading_font: Generated<string>;
  email_sender_name: string | null;
  email_reply_to: string | null;
  contrast_warnings: Generated<Json>;
  resolved_tokens: Generated<Json>;
  version: Generated<number>;
  updated_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface WorkspaceDomains {
  id: Generated<string>;
  workspace_id: string;
  hostname: string;
  verified_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface WorkspaceMembers {
  id: Generated<string>;
  workspace_id: string;
  user_id: string;
  role: string;
  status: Generated<string>;
  title: string | null;
  review_capacity: number | null;
  mfa_required: Generated<boolean>;
  invited_by: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface WorkspaceSettings {
  workspace_id: string;
  scan_required: Generated<boolean>;
  retention_days: Generated<number>;
  overdue_report_hold: Generated<boolean>;
  second_approval_threshold_cents: Generated<number>;
  action_tier_overrides: Generated<Json>;
  transparency_enabled: Generated<boolean>;
  email_domain: string | null;
  email_domain_status: Generated<string>;
  sso_enabled: Generated<boolean>;
  opengrants_syndication: Generated<boolean>;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface Workspaces {
  id: Generated<string>;
  slug: string;
  name: string;
  timezone: Generated<string>;
  status: Generated<string>;
  plan: Generated<string>;
  feature_flags: Generated<Json>;
  fiscal_year_start_month: Generated<number>;
  public_contact_email: string | null;
  about_md: string | null;
  created_at: Generated<Timestamp>;
  last_modified_at: Generated<Timestamp>;
}

export interface DB {
  agent_clients: AgentClients;
  agent_grants: AgentGrants;
  agent_policies: AgentPolicies;
  agent_tasks: AgentTasks;
  agreements: Agreements;
  analytics_budget_by_program: AnalyticsBudgetByProgram;
  analytics_cashflow_forecast: AnalyticsCashflowForecast;
  analytics_demographics: AnalyticsDemographics;
  analytics_outcomes: AnalyticsOutcomes;
  analytics_pipeline_funnel: AnalyticsPipelineFunnel;
  analytics_portfolio_by_cause: AnalyticsPortfolioByCause;
  analytics_portfolio_by_county: AnalyticsPortfolioByCounty;
  analytics_time_in_stage: AnalyticsTimeInStage;
  api_keys: ApiKeys;
  applicant_extensions: ApplicantExtensions;
  applicant_org_members: ApplicantOrgMembers;
  applicant_orgs: ApplicantOrgs;
  application_collaborators: ApplicationCollaborators;
  application_comments: ApplicationComments;
  application_duplicate_dismissals: ApplicationDuplicateDismissals;
  application_submissions: ApplicationSubmissions;
  applications: Applications;
  approval_requests: ApprovalRequests;
  attachments: Attachments;
  audit_log: AuditLog;
  award_conditions: AwardConditions;
  awards: Awards;
  bank_accounts: BankAccounts;
  bank_connections: BankConnections;
  bank_transactions: BankTransactions;
  bulk_messages: BulkMessages;
  change_requests: ChangeRequests;
  coi_declarations: CoiDeclarations;
  competition_forms: CompetitionForms;
  competition_invites: CompetitionInvites;
  competitions: Competitions;
  custom_field_definitions: CustomFieldDefinitions;
  decisions: Decisions;
  demographic_responses: DemographicResponses;
  deployment_requests: DeploymentRequests;
  dev_outbox: DevOutbox;
  diligence_checks: DiligenceChecks;
  docket_items: DocketItems;
  dockets: Dockets;
  eligibility_results: EligibilityResults;
  eligibility_rules: EligibilityRules;
  email_deliveries: EmailDeliveries;
  email_events: EmailEvents;
  email_templates: EmailTemplates;
  exports: Exports;
  form_responses: FormResponses;
  form_templates: FormTemplates;
  form_versions: FormVersions;
  forms: Forms;
  grantee_profiles: GranteeProfiles;
  idempotency_keys: IdempotencyKeys;
  indicator_values: IndicatorValues;
  indicators: Indicators;
  installments: Installments;
  internal_notes: InternalNotes;
  invitations: Invitations;
  irs_exempt_orgs: IrsExemptOrgs;
  messages: Messages;
  notification_rules: NotificationRules;
  notifications: Notifications;
  oauth_authorization_codes: OauthAuthorizationCodes;
  oauth_pending_authorizations: OauthPendingAuthorizations;
  opportunities: Opportunities;
  opportunity_subscriptions: OpportunitySubscriptions;
  org_addresses: OrgAddresses;
  org_documents: OrgDocuments;
  outbox: Outbox;
  panel_notes: PanelNotes;
  panels: Panels;
  payees: Payees;
  payment_approvals: PaymentApprovals;
  payment_batches: PaymentBatches;
  payment_schedules: PaymentSchedules;
  payments: Payments;
  personal_access_tokens: PersonalAccessTokens;
  platform_operators: PlatformOperators;
  profiles: Profiles;
  program_accounts: ProgramAccounts;
  program_budgets: ProgramBudgets;
  programs: Programs;
  public_awards: PublicAwards;
  public_programs: PublicPrograms;
  question_bank_items: QuestionBankItems;
  rail_events: RailEvents;
  rate_limit_buckets: RateLimitBuckets;
  recon_exceptions: ReconExceptions;
  report_requirements: ReportRequirements;
  report_submissions: ReportSubmissions;
  review_assignments: ReviewAssignments;
  review_scores: ReviewScores;
  review_stages: ReviewStages;
  reviews: Reviews;
  rubric_criteria: RubricCriteria;
  rubrics: Rubrics;
  sanctions_entries: SanctionsEntries;
  sanctions_screenings: SanctionsScreenings;
  saved_views: SavedViews;
  signatures: Signatures;
  site_visits: SiteVisits;
  status_history: StatusHistory;
  support_access_grants: SupportAccessGrants;
  taxonomy_terms: TaxonomyTerms;
  threads: Threads;
  votes: Votes;
  webhook_deliveries: WebhookDeliveries;
  webhook_endpoints: WebhookEndpoints;
  workspace_brand: WorkspaceBrand;
  workspace_domains: WorkspaceDomains;
  workspace_members: WorkspaceMembers;
  workspace_settings: WorkspaceSettings;
  workspaces: Workspaces;
}
