// SPDX-License-Identifier: AGPL-3.0-only
// Maps the lucide icon names used in @gms/domain statuses to lucide-react components.
// Explicit imports keep bundles small (no whole-library icon map).
import {
  AlarmClock,
  Archive,
  BadgeCheck,
  Ban,
  Bot,
  Calendar,
  CalendarClock,
  CheckCheck,
  Circle,
  CircleAlert,
  CircleArrowRight,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CirclePause,
  CircleSlash,
  CircleX,
  Clock,
  ClockAlert,
  FilePenLine,
  Flag,
  Hand,
  Landmark,
  Layers,
  Loader,
  Mail,
  MessageSquareWarning,
  PencilLine,
  ScanSearch,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  TriangleAlert,
  Undo2,
  UserCheck,
  UserX,
  type LucideIcon,
} from 'lucide-react';

export const STATUS_ICONS: Record<string, LucideIcon> = {
  'alarm-clock': AlarmClock,
  archive: Archive,
  'arrow-right-circle': CircleArrowRight,
  'circle-arrow-right': CircleArrowRight,
  'badge-check': BadgeCheck,
  ban: Ban,
  bot: Bot,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'check-check': CheckCheck,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  'circle-slash': CircleSlash,
  'circle-x': CircleX,
  clock: Clock,
  'clock-alert': ClockAlert,
  'file-signature': FilePenLine,
  'file-pen-line': FilePenLine,
  flag: Flag,
  hand: Hand,
  landmark: Landmark,
  layers: Layers,
  loader: Loader,
  mail: Mail,
  'message-square-warning': MessageSquareWarning,
  'pause-circle': CirclePause,
  'circle-pause': CirclePause,
  'pencil-line': PencilLine,
  'scan-search': ScanSearch,
  send: Send,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-x': ShieldX,
  'triangle-alert': TriangleAlert,
  'undo-2': Undo2,
  'user-check': UserCheck,
  'user-x': UserX,
};

/** Lucide component for a kebab-case icon name; falls back to a plain circle. */
export function statusIcon(name: string): LucideIcon {
  return STATUS_ICONS[name] ?? Circle;
}
