// SPDX-License-Identifier: AGPL-3.0-only
// Generates packages/db/src/types.gen.ts (Kysely table interfaces) from the live database schema.
// Mapping matches the pg type parsers in packages/db/src/client.ts (int8/numeric -> number, timestamps -> ISO string).
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';
import { databaseUrl, repoRoot } from '../packages/db/src/env';

const client = new pg.Client({ connectionString: databaseUrl() });
await client.connect();

const cols = await client.query<{
  table_schema: string;
  table_name: string;
  column_name: string;
  udt_name: string;
  data_type: string;
  is_nullable: 'YES' | 'NO';
  column_default: string | null;
  is_generated: string;
  is_identity: string;
  table_type: string;
}>(`
  select c.table_schema, c.table_name, c.column_name, c.udt_name, c.data_type, c.is_nullable, c.column_default,
         c.is_generated, c.is_identity, t.table_type
  from information_schema.columns c
  join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
  where c.table_schema in ('public', 'analytics')
  order by c.table_schema, c.table_name, c.ordinal_position`);
await client.end();

function tsType(udt: string): string {
  const base = udt.startsWith('_') ? udt.slice(1) : udt;
  let t: string;
  switch (base) {
    case 'int2':
    case 'int4':
    case 'int8':
    case 'float4':
    case 'float8':
    case 'numeric':
      t = 'number';
      break;
    case 'bool':
      t = 'boolean';
      break;
    case 'json':
    case 'jsonb':
      t = 'Json';
      break;
    case 'timestamptz':
    case 'timestamp':
      t = 'Timestamp';
      break;
    default:
      t = 'string';
  }
  return udt.startsWith('_') ? (t === 'Timestamp' ? 'string[]' : `${t}[]`) : t;
}

function pascal(s: string): string {
  return s.replace(/(^|_)([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
}

const tables = new Map<string, { schema: string; name: string; view: boolean; lines: string[] }>();
for (const c of cols.rows) {
  const key = `${c.table_schema}.${c.table_name}`;
  let t = tables.get(key);
  if (!t) {
    t = { schema: c.table_schema, name: c.table_name, view: c.table_type !== 'BASE TABLE', lines: [] };
    tables.set(key, t);
  }
  let ty = tsType(c.udt_name);
  if (c.is_nullable === 'YES') ty = `${ty} | null`;
  const generatedAlways = c.is_generated === 'ALWAYS' || (c.is_identity === 'YES' && c.column_default === null && false);
  if (!t.view && generatedAlways) ty = `GeneratedAlways<${ty}>`;
  else if (!t.view && (c.column_default !== null || c.is_identity === 'YES')) ty = `Generated<${ty}>`;
  t.lines.push(`  ${c.column_name}: ${ty};`);
}

let out = `// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by \`pnpm db:types\` from the database schema. Do not edit by hand.
import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type GeneratedAlways<T> = ColumnType<T, never, never>;
export type Timestamp = ColumnType<string, string | Date, string | Date>;
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type Json = ColumnType<JsonValue, JsonValue | string, JsonValue | string>;

`;
const dbLines: string[] = [];
for (const t of tables.values()) {
  const iface = (t.schema === 'public' ? '' : pascal(t.schema)) + pascal(t.name);
  out += `export interface ${iface} {\n${t.lines.join('\n')}\n}\n\n`;
  dbLines.push(`  ${t.schema === 'public' ? t.name : `'${t.schema}.${t.name}'`}: ${iface};`);
}
out += `export interface DB {\n${dbLines.join('\n')}\n}\n`;
writeFileSync(join(repoRoot(), 'packages', 'db', 'src', 'types.gen.ts'), out);
console.log(`[db:types] wrote ${tables.size} tables/views`);
