// SPDX-License-Identifier: AGPL-3.0-only
// `pnpm doctor`: detects capabilities, prints which adapters are active, and writes ENVIRONMENT.md.
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';
import { databaseUrl, loadDotEnv, repoRoot } from '../packages/db/src/env';
import { detectAdapters, detectDbTier, toolVersions } from './lib/detect';

loadDotEnv();
const tier = await detectDbTier();
const tools = toolVersions();
const adapters = detectAdapters();

let dbStatus = 'unreachable';
let dbVersion = '';
try {
  const c = new pg.Client({ connectionString: databaseUrl(), connectionTimeoutMillis: 3000 });
  await c.connect();
  dbVersion = (await c.query<{ v: string }>('select version() as v')).rows[0]!.v.split(',')[0]!;
  const m = await c
    .query<{ n: string }>('select count(*)::text as n from gms_meta.schema_migrations')
    .then((r) => r.rows[0]!.n)
    .catch(() => '0');
  dbStatus = `reachable, ${m} migration(s) applied`;
  await c.end();
} catch {
  dbStatus = 'unreachable (run `pnpm db:up`)';
}

const e = process.env;
const live = {
  'Mercury sandbox': Boolean(e.MERCURY_ENV === 'sandbox' && e.MERCURY_API_TOKEN),
  'Resend (delivered@resend.dev)': Boolean(e.RESEND_API_KEY),
  'Supabase Auth magic link': Boolean(e.SUPABASE_URL && e.SUPABASE_SERVICE_ROLE_KEY),
  'Netlify preview deploy': Boolean(e.NETLIFY_AUTH_TOKEN && e.NETLIFY_SITE_ID),
  // Pushing needs a configured remote as well as credentials (gh login or GITHUB_TOKEN).
  'GitHub push / draft PR': hasGitRemote() && (Boolean(e.GITHUB_TOKEN) || tools.gh !== null),
};

function hasGitRemote(): boolean {
  const r = spawnSync('git', ['remote'], { cwd: repoRoot(), encoding: 'utf8' });
  return r.status === 0 && r.stdout.trim().length > 0;
}

const lines: string[] = [];
lines.push('# ENVIRONMENT', '');
lines.push(`Generated by \`pnpm doctor\` on ${new Date().toISOString()}. Re-run it whenever the environment changes.`, '');
lines.push('## Database', '');
lines.push(`- **Tier:** ${tier.tier} — ${tier.reason}`);
lines.push(`- **Connection:** ${databaseUrl().replace(/:[^:@/]+@/, ':****@')} (${dbStatus})`);
if (dbVersion) lines.push(`- **Server:** ${dbVersion}`);
lines.push('', '## Adapters', '', '| Adapter | Active | Real? | Note |', '|---|---|---|---|');
for (const a of adapters) lines.push(`| ${a.name} | ${a.active} | ${a.real ? 'yes' : 'fake'} | ${a.note} |`);
lines.push('', '## Tools', '', '| Tool | Version |', '|---|---|');
for (const [k, v] of Object.entries(tools)) lines.push(`| ${k} | ${v ?? 'not available'} |`);
lines.push('', '## Live integration tests', '', '| Test | Runs? |', '|---|---|');
for (const [k, v] of Object.entries(live)) lines.push(`| ${k} | ${v ? 'yes' : 'skipped (no credentials)'} |`);
lines.push(
  '',
  '## Modes',
  '',
  `- GMS_MODE=${e.GMS_MODE ?? 'single'} · DEFAULT_TENANT=${e.DEFAULT_TENANT ?? 'halcyon'} · GMS_ROOT_DOMAIN=${e.GMS_ROOT_DOMAIN ?? 'localhost:3000'} · GMS_AUTH_MODE=${
    e.GMS_AUTH_MODE ?? (e.SUPABASE_URL ? 'supabase' : 'test')
  }`,
  '',
  '## Notes',
  '',
  '- Docker Desktop is installed but its daemon did not start during this run, so tier 1 (local Supabase) was not used.',
  '- No Supabase, Mercury, Resend or Netlify credentials were present; every external dependency ran on its fake adapter. The repository has no git remote, so nothing was pushed.',
  '',
);
writeFileSync(join(repoRoot(), 'ENVIRONMENT.md'), lines.join('\n'));

console.log(`\nGMS doctor\n`);
console.log(`Database tier : ${tier.tier} (${tier.reason})`);
console.log(`Database      : ${dbStatus}`);
console.log(`\nAdapters:`);
for (const a of adapters) console.log(`  ${a.name.padEnd(16)} ${a.active.padEnd(22)} ${a.real ? 'real' : 'fake'}  ${a.note}`);
console.log(`\nWrote ENVIRONMENT.md`);
