// SPDX-License-Identifier: AGPL-3.0-only
// Writes docs/rls-coverage.md: every table in public / gms_private, whether RLS is on, its policies
// (command + roles), guard triggers, and whether the RLS matrix test covers it.
//
//   npx tsx scripts/rls-report.ts
//
// Builds a throwaway database with every migration applied (same server as the DB tests), so the
// report always reflects supabase/migrations, not whatever state a dev database is in.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { sql } from '../packages/db/src/client';
import { repoRoot } from '../packages/db/src/env';
import { createTestDatabase } from '../packages/db/src/testing';
import { MATRIX, OPS, assertionCount } from '../packages/db/test/rls-expectations';
import { PRINCIPALS } from '../packages/db/test/world';

interface RelRow {
  schema: string;
  name: string;
  kind: string;
  rls: boolean;
}
interface PolicyRow {
  schema: string;
  table: string;
  name: string;
  cmd: string;
  roles: string[] | string;
  permissive: string;
}
interface TriggerRow {
  schema: string;
  table: string;
  name: string;
}

const t = await createTestDatabase('gms_rls_report');
try {
  const rels = (
    await sql<RelRow>`
      select n.nspname as schema, c.relname as name, c.relkind::text as kind, c.relrowsecurity as rls
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
      where n.nspname in ('public', 'gms_private') and c.relkind in ('r', 'p', 'v', 'm')
      order by 1, 2`.execute(t.db)
  ).rows;
  const policies = (
    await sql<PolicyRow>`
      select schemaname as schema, tablename as table, policyname as name, cmd, roles::text[] as roles, permissive
      from pg_policies where schemaname in ('public', 'gms_private') order by 1, 2, 3`.execute(t.db)
  ).rows;
  const triggers = (
    await sql<TriggerRow>`
      select n.nspname as schema, c.relname as table, tg.tgname as name
      from pg_trigger tg join pg_class c on c.oid = tg.tgrelid join pg_namespace n on n.oid = c.relnamespace
      where not tg.tgisinternal and n.nspname in ('public', 'gms_private') and tg.tgname <> 'touch_last_modified'
      order by 1, 2, 3`.execute(t.db)
  ).rows;

  const matrix = new Map(MATRIX.map((s) => [s.table, s]));
  const roles = (r: string[] | string) => (Array.isArray(r) ? r : String(r).replace(/[{}]/g, '').split(',')).join(', ');
  const cell = (list: readonly string[]) => (list.length === 0 ? '—' : list.length === PRINCIPALS.length ? 'everyone' : list.join(', '));

  const lines: string[] = [];
  lines.push('<!-- SPDX-License-Identifier: AGPL-3.0-only -->');
  lines.push('<!-- Generated by `npx tsx scripts/rls-report.ts`. Do not edit by hand. -->');
  lines.push('');
  lines.push('# RLS coverage');
  lines.push('');
  lines.push(
    'Every table in `public` and `gms_private`, whether row-level security is enabled, its policies, its guard triggers, ' +
      'and whether the RLS matrix test (`packages/db/test/rls-matrix.db.test.ts`, data in `packages/db/test/rls-expectations.ts`) covers it.',
  );
  lines.push('');
  const tables = rels.filter((r) => r.kind === 'r' || r.kind === 'p');
  const publicRels = rels.filter((r) => r.schema === 'public');
  const covered = publicRels.filter((r) => matrix.has(r.name)).length;
  lines.push(`- Relations: ${rels.length} (${tables.length} tables, ${rels.length - tables.length} view(s))`);
  lines.push(`- RLS enabled: ${tables.filter((r) => r.rls).length} / ${tables.length} tables`);
  lines.push(`- Policies: ${policies.length}`);
  lines.push(`- Matrix coverage: ${covered} / ${publicRels.length} public relations; ${assertionCount()} allow/deny assertions over ${PRINCIPALS.length} principals`);
  lines.push('');
  lines.push(`Principals: ${PRINCIPALS.map((p) => `\`${p}\``).join(', ')}.`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Table | Kind | RLS | Policies | Guard triggers | Matrix |');
  lines.push('|---|---|---|---|---|---|');
  for (const r of rels) {
    const pol = policies.filter((p) => p.schema === r.schema && p.table === r.name).length;
    const trg = triggers.filter((x) => x.schema === r.schema && x.table === r.name).length;
    const kind = r.kind === 'v' ? 'view' : r.kind === 'm' ? 'matview' : 'table';
    const rls = r.kind === 'v' || r.kind === 'm' ? 'n/a' : r.rls ? 'on' : '**OFF**';
    const mx = r.schema === 'gms_private' ? 'service only' : matrix.has(r.name) ? 'yes' : '**NO**';
    lines.push(`| \`${r.schema}.${r.name}\` | ${kind} | ${rls} | ${pol} | ${trg} | ${mx} |`);
  }
  lines.push('');
  lines.push('## Details');
  for (const r of rels) {
    lines.push('');
    lines.push(`### \`${r.schema}.${r.name}\``);
    lines.push('');
    const spec = matrix.get(r.name);
    if (spec?.note) {
      lines.push(spec.note);
      lines.push('');
    }
    const pols = policies.filter((p) => p.schema === r.schema && p.table === r.name);
    if (r.kind === 'v' || r.kind === 'm') {
      lines.push('View (runs with its owner\'s privileges; grants decide who can read it).');
    } else if (pols.length === 0) {
      lines.push(r.rls ? 'RLS on, no policies: request roles can neither read nor write (service only).' : '**RLS is OFF.**');
    } else {
      lines.push('| Policy | Command | Roles | Type |');
      lines.push('|---|---|---|---|');
      for (const p of pols) lines.push(`| \`${p.name}\` | ${p.cmd} | ${roles(p.roles)} | ${p.permissive.toLowerCase()} |`);
    }
    const trg = triggers.filter((x) => x.schema === r.schema && x.table === r.name);
    if (trg.length) {
      lines.push('');
      lines.push(`Triggers: ${trg.map((x) => `\`${x.name}\``).join(', ')}`);
    }
    if (spec) {
      lines.push('');
      lines.push('| Op | Allowed (everyone else denied) |');
      lines.push('|---|---|');
      for (const op of spec.kind === 'view' ? (['select'] as const) : OPS) lines.push(`| ${op} | ${cell(spec.allow[op])} |`);
    } else if (r.schema === 'public') {
      lines.push('');
      lines.push('**Not covered by the RLS matrix.**');
    }
  }
  lines.push('');
  const out = join(repoRoot(), 'docs', 'rls-coverage.md');
  writeFileSync(out, lines.join('\n'));
  console.log(`[rls-report] wrote ${out} (${rels.length} relations, ${policies.length} policies, ${covered}/${publicRels.length} covered)`);
} finally {
  await t.drop();
}
